include ./theme.conf

#: Fonts {{{
font_family           FiraCode Nerd Font
bold_font             FiraCode Nerd Font
italic_font           FiraCode Nerd Font
bold_italic_font      FiraCode Nerd Font
font_size           9.0
adjust_line_height  5
adjust_column_width 1
disable_ligatures   never

#: Bell 
enable_audio_bell no

window_margin_width 10

# vim:fileencoding=utf-8:ft=conf:foldmethod=marker
